import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import type { StepContext } from 'tinydag';

interface CountRow {
  category: string;
  count: bigint;
}

export default async function makeReport(ctx: StepContext): Promise<void> {
  const warehouse = ctx.connections.warehouse;
  if (!warehouse) throw new Error('warehouse connection not available');

  const threshold = Number(ctx.vars.warning_threshold ?? '0');
  if (!Number.isFinite(threshold)) {
    throw new Error(`warning_threshold must be a number, got: ${ctx.vars.warning_threshold}`);
  }

  const rows = await warehouse.query<CountRow>(
    'SELECT category, count FROM event_counts ORDER BY count DESC',
  );
  ctx.logger.info(`fetched ${rows.length} categories from DuckDB`);

  const lines: string[] = [];
  lines.push(`# Event Report`, '');
  lines.push(`Generated by pipeline \`${ctx.pipelineName}\` (step: \`${ctx.stepId}\`).`, '');
  lines.push(`## Top categories`, '');
  lines.push(`| Category | Count |`);
  lines.push(`|----------|------:|`);
  for (const r of rows) {
    lines.push(`| ${r.category} | ${r.count} |`);
  }
  lines.push('');

  const lowVolume = rows.filter((r) => Number(r.count) < threshold);
  if (lowVolume.length > 0) {
    lines.push(`## Warnings (count < ${threshold})`, '');
    for (const r of lowVolume) {
      lines.push(`- **${r.category}** — only ${r.count} events`);
    }
    lines.push('');
    ctx.logger.warn(`${lowVolume.length} categories below threshold (${threshold})`);
  } else {
    lines.push(`_All categories meet the ${threshold}-event threshold._`, '');
  }

  const outPath = resolve(process.cwd(), 'output/report.md');
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, lines.join('\n'));
  ctx.logger.info(`wrote ${outPath}`);
}
